import { SEORule } from '@/types/pipeline';

export const SEO_RULES_LIBRARY: SEORule[] = [
  {
    id: 'kw-density',
    category: 'seo',
    name: 'Keyword Density',
    nameAr: 'كثافة الكلمات المفتاحية',
    description: 'الحفاظ على كثافة مفتاحية مثالية (1-2%) في المقال بالكامل',
    fullPrompt: 'Maintain keyword density of 1-2% for the primary keyword. Use the primary keyword naturally in the first 100 words, in at least one H2 heading, and distribute it evenly throughout the content. Avoid keyword stuffing.',
    enabled: true,
  },
  {
    id: 'heading-kw',
    category: 'seo',
    name: 'Keywords in Headings',
    nameAr: 'الكلمات المفتاحية في العناوين',
    description: 'تضمين الكلمات المفتاحية بشكل استراتيجي في عناوين H1-H3',
    fullPrompt: 'Include the primary keyword in the H1 heading and in at least 2 H2 headings. Use secondary keywords and LSI keywords in H3 subheadings. Ensure headings read naturally and are not stuffed with keywords.',
    enabled: true,
  },
  {
    id: 'internal-links',
    category: 'seo',
    name: 'Internal Linking',
    nameAr: 'الروابط الداخلية',
    description: 'اقتراح 3-5 فرص للربط الداخلي مع نص رابط وصفي',
    fullPrompt: 'Suggest 3-5 internal linking opportunities within the content. Mark suggested anchor text with [INTERNAL_LINK: anchor text -> suggested topic/page]. Use descriptive anchor text that includes relevant keywords.',
    enabled: true,
  },
  {
    id: 'meta-tags',
    category: 'seo',
    name: 'Meta Title & Description',
    nameAr: 'العنوان والوصف التعريفي',
    description: 'إنشاء عنوان meta (≤60 حرف) ووصف meta (≤160 حرف) محسّنَين',
    fullPrompt: 'At the end of the article, generate: 1) An SEO-optimized meta title (≤60 characters) that includes the primary keyword near the beginning. 2) A compelling meta description (≤160 characters) that includes the primary keyword and a call-to-action.',
    enabled: true,
  },
  {
    id: 'schema',
    category: 'seo',
    name: 'Schema Markup',
    nameAr: 'ترميز البيانات المنظمة',
    description: 'تضمين ترميز schema.org بتنسيق JSON-LD (Article + FAQ)',
    fullPrompt: 'At the end of the article, provide schema.org structured data recommendations in JSON-LD format. Include Article schema with headline, description, author, and datePublished. If applicable, include FAQ schema for any question-answer sections.',
    enabled: false,
  },
  {
    id: 'readability',
    category: 'seo',
    name: 'Readability',
    nameAr: 'سهولة القراءة',
    description: 'فقرات قصيرة (2-3 جمل)، كلمات ربط، قوائم، لغة بسيطة',
    fullPrompt: 'Write at an 8th-grade reading level. Use short paragraphs (2-3 sentences max). Use transition words between paragraphs. Break up long sections with bullet points or numbered lists. Use simple, clear language.',
    enabled: true,
  },
  {
    id: 'featured-snippet',
    category: 'visual',
    name: 'Featured Snippet',
    nameAr: 'المقتطف المميز',
    description: 'هيكلة قسم واحد على الأقل كإجابة مباشرة لمقتطف جوجل المميز',
    fullPrompt: 'Structure at least one section as a direct answer suitable for a Google featured snippet. This could be: a concise definition (40-60 words), a numbered step-by-step list, or a comparison table. Place this near the top of the article.',
    enabled: true,
  },
  {
    id: 'eeat',
    category: 'seo',
    name: 'E-E-A-T Signals',
    nameAr: 'إشارات الخبرة والموثوقية',
    description: 'إشارات خبرة المؤلف، مصادر موثوقة، إحصائيات ودراسات',
    fullPrompt: 'Include author expertise signals throughout the content. Cite at least 2-3 authoritative sources. Include specific data, statistics, or research findings where relevant. Demonstrate first-hand experience with the topic. Use confident, authoritative language.',
    enabled: true,
  },
  {
    id: 'faq',
    category: 'seo',
    name: 'FAQ Section',
    nameAr: 'قسم الأسئلة الشائعة',
    description: 'إنشاء قسم أسئلة شائعة (5-8 أسئلة) من عبارات البحث',
    fullPrompt: 'Generate a FAQ section at the end of the article with 5-8 questions. Use the question phrases provided in the SEO data. Each answer should be concise (2-3 sentences) and directly address the question. Structure as an HTML definition list or accordion-friendly format.',
    enabled: true,
  },
  {
    id: 'img-alt',
    category: 'visual',
    name: 'Image Alt Text',
    nameAr: 'نص بديل للصور',
    description: 'اقتراح 5-10 صور مع نص بديل محسّن يتضمن كلمات مفتاحية',
    fullPrompt: 'Suggest 5-10 relevant images throughout the article. For each suggestion, provide: [IMAGE: description of the image | alt="SEO-optimized alt text including relevant keyword"]. Place image suggestions at logical break points in the content.',
    enabled: false,
  },
  {
    id: 'aeo-tldr',
    category: 'visual',
    name: 'AEO Quick Answers',
    nameAr: 'إجابات سريعة (AEO)',
    description: 'صندوق خلاصة تحت H1 وكل H2 رئيسي — طُعم لمحركات AI (SGE, Perplexity)',
    fullPrompt: 'ANSWER ENGINE OPTIMIZATION: Immediately after the H1 and after each major H2, insert a "Quick Answer" box formatted as: <div class="quick-answer"><strong>الخلاصة:</strong> [45-word direct answer OR 3 bullet points]</div>. These must directly answer the search intent for that section in a concise, citeable format. AI search engines (SGE, Perplexity, SearchGPT) will extract these as citations.',
    enabled: true,
  },
  {
    id: 'grounding-stats',
    category: 'seo',
    name: 'Live Statistics',
    nameAr: 'إحصائيات حية ومصادر',
    description: 'جلب إحصائيتين حديثتين (2024/2025) مع روابط خارجية للمصادر',
    fullPrompt: 'Include at least 2 recent statistics (2024 or 2025) with real source citations. Format as: "وفقاً لـ [Source Name]، [statistic]" and include the actual URL as an outbound link. This grounds the content in verifiable data and prevents AI hallucination.',
    enabled: true,
  },
  {
    id: 'mermaid-diagrams',
    category: 'visual',
    name: 'Mermaid Diagrams',
    nameAr: 'رسوم بيانية تفاعلية',
    description: 'توليد 1-2 رسم بياني Mermaid.js (خرائط ذهنية، مخططات انسيابية) — جوجل يكافئ الرسوم الأصلية',
    fullPrompt: 'Generate 1-2 Mermaid.js diagrams within the article. For complex processes, use a flowchart (graph TD). For hierarchies, use a mindmap. Wrap each in: <div class="mermaid-diagram"><pre class="mermaid">graph TD; A[Start] --> B[Step];</pre></div>. Place diagrams at logical break points to increase dwell time. Diagrams must be relevant to the content and add visual value.',
    enabled: false,
  },
  {
    id: 'comparison-tables',
    category: 'visual',
    name: 'Comparison Tables',
    nameAr: 'جداول مقارنة ذكية',
    description: 'توليد جدول مقارنة واحد على الأقل — السلاح الأول لاقتناص Featured Snippets',
    fullPrompt: 'Include at least ONE comparison table (<table>) in the article. The table must: have a clear <caption>, use <th> headers, have 3+ rows and 3+ columns, compare real alternatives/options relevant to the topic. This is the #1 format Google uses for Featured Snippet tables. Style with class="comparison-table" for rich formatting.',
    enabled: true,
  },
  {
    id: 'sge-bait',
    category: 'visual',
    name: 'SGE/AI Bait Boxes',
    nameAr: 'صناديق اصطياد محركات AI',
    description: 'صندوق إجابة قاطعة (45 كلمة) تحت كل عنوان رئيسي — طُعم لـ SGE و Perplexity و SearchGPT',
    fullPrompt: 'SGE BAIT PROTOCOL: Under the H1 and under EVERY H2, insert: <div class="sge-bait-box"><strong>باختصار:</strong> [EXACTLY 45 words that directly answer the search intent for this section. Start with a definitive statement, not a question. Include the primary keyword. This must be self-contained and quotable by AI search engines.]</div>. These boxes are designed to be cited by SGE, Perplexity, and SearchGPT.',
    enabled: false,
  },
  // ─── Semantic Writing Rules (from SemanticsX spec) ───
  {
    id: 'immediate-answer',
    category: 'semantic',
    name: 'Immediate Answering',
    nameAr: 'الإجابة الفورية',
    description: 'أجب على السؤال فوراً ثم فصّل — لا تؤخر الإجابة',
    fullPrompt: 'Do not distance the question from the answer. Answer the question right away to provide clarity, then elaborate. Example: For "How much caffeine is in coffee?" immediately answer "There is 95 mg of caffeine in coffee." then give details. Do not delay the answer with background context.',
    enabled: true,
  },
  {
    id: 'no-analogies',
    category: 'semantic',
    name: 'No Analogies',
    nameAr: 'بدون تشبيهات',
    description: 'تجنب التشبيهات — تُربك محركات البحث وتُقلل الوضوح',
    fullPrompt: 'Don\'t use analogies. An analogy is a way of explaining something by comparing it to something else that is similar. Avoid using analogies as they can confuse search engines and reduce clarity. Explain concepts directly instead.',
    enabled: false,
  },
  {
    id: 'clear-pronouns',
    category: 'semantic',
    name: 'Clear Pronoun Usage',
    nameAr: 'وضوح الضمائر',
    description: 'تجنب أخطاء الإسناد — وضّح لمن يعود الضمير',
    fullPrompt: 'Avoid coreference errors. Improper pronoun usage results in a "coreference error" where search engines struggle to understand which entity the pronoun refers to. Example error: "Joe Rogan did a podcast with Elon Musk, and he shared his thoughts on finance." — It\'s unclear who "he" refers to. Always use the entity name when ambiguity is possible.',
    enabled: true,
  },
  {
    id: 'sentence-efficiency',
    category: 'semantic',
    name: 'Sentence Efficiency',
    nameAr: 'كفاءة الجمل',
    description: 'لا تُنشئ جملة إضافية بدون سبب منطقي — كل جملة = رمز جديد',
    fullPrompt: 'Don\'t create an extra sentence if there is no logical reason. With each new sentence, search engines use a new token. Combine related facts into one sentence. Example: Instead of "Tanjiro is 25 years old. His birthdate is Dec 2, 2002." write "Tanjiro is 25 years old and his birthdate is Dec 2, 2002." — fewer tokens, same information.',
    enabled: false,
  },
  {
    id: 'abbreviations',
    category: 'semantic',
    name: 'Abbreviations First Mention',
    nameAr: 'الاختصارات عند أول ذكر',
    description: 'استخدم الاختصار بين قوسين عند الذكر الأول',
    fullPrompt: 'Always use the abbreviation in parentheses on first mention. When you introduce an entity or concept for the first time, include its abbreviation right after the full term. Example: "Bitcoin (BTC) is the main cryptocurrency asset." not "Bitcoin is the main cryptocurrency asset."',
    enabled: true,
  },
  {
    id: 'no-back-reference',
    category: 'semantic',
    name: 'No Back-Referencing',
    nameAr: 'عدم الإحالة للخلف',
    description: 'لا تُحيل القارئ لأقسام سابقة — أعد ذكر المعلومة مباشرة',
    fullPrompt: 'Do not send the reader or text processors to the back of the article. Do not say "As stated before", "As mentioned earlier", or "As explained in section X". Instead, restate the information directly. This keeps content flow uninterrupted and makes it easier for readers and search engines to process.',
    enabled: true,
  },
  {
    id: 'safe-answers',
    category: 'semantic',
    name: 'Comprehensive Answers',
    nameAr: 'إجابات شاملة وآمنة',
    description: 'أعطِ إجابات شاملة متعددة المصادر والعوامل',
    fullPrompt: 'Give safe, comprehensive answers. When answering a question, include: the direct answer, list of factors that affect it, real-world user experiences, manufacturer/expert opinions, and historical observations where relevant. Cover the topic from multiple angles for authoritative, complete answers.',
    enabled: false,
  },
  {
    id: 'bold-answer',
    category: 'semantic',
    name: 'Bold the Answer',
    nameAr: 'تمييز الإجابة بالخط العريض',
    description: 'ميّز الإجابة بالخط العريض وليس مصطلح البحث',
    fullPrompt: 'Bold the answer, not the search term. When answering a question, bold the informative answer part, not the keyword. Example: Query "What is a Penguin?" → "A penguin is **a flightless seabird**." Signal the answer part, not the relevance.',
    enabled: true,
  },
  {
    id: 'if-placement',
    category: 'semantic',
    name: 'If-Statement Placement',
    nameAr: 'ترتيب جمل الشرط',
    description: 'ضع جملة "إذا" في الجزء الثاني من الجملة',
    fullPrompt: 'Put "if" statements in the second part of the sentence. State what to do first, then explain the condition. "If it rains, take an umbrella." → Less preferred. "Take an umbrella, if it rains." → Better. The action comes first, the condition second.',
    enabled: false,
  },
  {
    id: 'heading-text-match',
    category: 'semantic',
    name: 'Heading-Text Structure Match',
    nameAr: 'تطابق بنية العنوان والنص',
    description: 'طابق بنية أول جملة مع نوع العنوان',
    fullPrompt: 'Optimize subordinate text first sentence to match the heading structure. Heading: "How to do X..." → Supporting text must start with "To do X..." not "X is...". Match the adjectives, predicates, and nouns order between questions and answers for clarity and cohesion.',
    enabled: true,
  },
  {
    id: 'examples-after-plural',
    category: 'semantic',
    name: 'Examples After Plural Nouns',
    nameAr: 'أمثلة بعد الأسماء الجمعية',
    description: 'أعطِ أمثلة محددة بعد كل اسم جمع',
    fullPrompt: 'Give examples after a plural noun. When mentioning a plural quantity, always follow with specific examples. Example: "There are 40 different cryptocurrencies to trade on Coinbase, including Bitcoin and Ethereum." "There are 15 types of workouts available in the app, including yoga, HIIT, and strength training."',
    enabled: true,
  },
  {
    id: 'precise-verbs',
    category: 'semantic',
    name: 'Precise Verb Usage',
    nameAr: 'استخدام دقيق للأفعال',
    description: 'استخدم الفعل المناسب للسياق (زيادة/تحسين/تطوير)',
    fullPrompt: 'Understand context of verbs and determine predicates wisely. "Increase" signals measurable metrics/quantities. "Improve" signals skills or health outcomes that can be enhanced. "Develop" signals gradual skill acquisition or growth. Example: "Stretching can increase flexibility" vs "Practice will improve proficiency" vs "Working in a startup helps develop resilience."',
    enabled: false,
  },
  {
    id: 'expert-specificity',
    category: 'semantic',
    name: 'Expert-Level Specificity',
    nameAr: 'دقة الخبراء',
    description: 'كُن محدداً بالأرقام — الخبراء لا يستخدمون عبارات عامة',
    fullPrompt: 'Be specific when describing things. Experts are specific. Do not say "The symptoms of X disease..." — say "There are 6 severe symptoms of X disease: these are... There are 9 rare symptoms..." Do not say "The benefits are numerous" — say "Product Y offers 5 key benefits: X, Y, Z..."',
    enabled: true,
  },
  {
    id: 'use-numbers',
    category: 'semantic',
    name: 'Use Numeric Values',
    nameAr: 'استخدام الأرقام',
    description: 'حدّد الكمية دائماً — لا تقل "كثير" بل "5 أسباب رئيسية"',
    fullPrompt: 'Use numeric values. Do not say "There are many reasons..." — say "There are 5 main reasons...". Experts are specific. Always quantify when possible. Numbers signal authority and precision to both readers and search engines.',
    enabled: true,
  },
  {
    id: 'cut-fluff',
    category: 'semantic',
    name: 'Cut the Fluff',
    nameAr: 'إزالة الحشو',
    description: 'احذف كل الكلمات التي لا تحمل سياقاً أو معلومة',
    fullPrompt: 'Cut the fluff. Delete all contextless words. Wrong: "There is one more fact about electric cars that every driver should know, and it is the electric charger capacity. Also, according to the charger type, the battery charging time might vary." Correct: "Electric car charging time changes based on charger type. For example, X type charger is 5% faster than Y type." Remove filler, keep facts.',
    enabled: true,
  },
  {
    id: 'be-certain',
    category: 'semantic',
    name: 'Be Certain',
    nameAr: 'كُن واثقاً',
    description: 'لا تستخدم "ربما" أو "قد" أو "من المحتمل" — اذكر الحقائق بثقة',
    fullPrompt: 'Be certain. Do not use "might", "could", "maybe", "possibly", "perhaps", "it is believed that". State facts with certainty and confidence. "The sun rises every day." — Correct, a fact. Knowledge should be certain and definite. Hedging language signals low authority to search engines.',
    enabled: true,
  },
  {
    id: 'parallel-lists',
    category: 'semantic',
    name: 'Parallel List Structure',
    nameAr: 'قوائم متوازية البنية',
    description: 'استخدم نفس نوع الكلمة في بداية كل عنصر قائمة',
    fullPrompt: 'Use the same part of speech (word role) in the first word of each list item. If starting with a verb: "Ensure proper alignment. Clear unnecessary clutter. Spend time reviewing. Absorb useful information." If starting with a noun: "Coffee provides energy. Exercise boosts metabolism. Hydration improves skin." Consistent structure improves readability and SEO.',
    enabled: false,
  },
  {
    id: 'match-interrogative',
    category: 'semantic',
    name: 'Match Interrogative Context',
    nameAr: 'مطابقة سياق الاستفهام',
    description: 'أين = مكان أولاً، متى = زمان أولاً، كم = رقم أولاً',
    fullPrompt: 'Prioritize attributes and contexts based on the interrogative term. "Where" is a signal for place — answer with location first. "When" needs time first. "How much" needs a number first. Example: "Where does a penguin live?" → "Penguins live below the equator, in X, Y, Z geographies because..."',
    enabled: true,
  },
  {
    id: 'diverse-units',
    category: 'semantic',
    name: 'Diverse Measurement Units',
    nameAr: 'وحدات قياس متنوعة',
    description: 'اذكر وحدات قياس متعددة لإثراء المحتوى دلالياً',
    fullPrompt: 'When mentioning measurement units, always include multiple diverse units. Less enriched: "Drink 16-20 oz of water." More enriched: "Drink 16-20 oz (0.5-0.6 liters) of water." The second version has more entity connections (oz, liters, kg) and serves diverse users who process information with different unit systems.',
    enabled: false,
  },
  {
    id: 'boolean-answers',
    category: 'semantic',
    name: 'Boolean Answers',
    nameAr: 'إجابات نعم/لا',
    description: 'ابدأ إجابة أسئلة نعم/لا بـ "نعم" أو "لا" مباشرة',
    fullPrompt: 'Boolean questions should start with Yes or No. When answering a yes/no question, start with a clear "Yes" or "No", then elaborate with supporting details. Example: "Does water in food help?" → "Yes, eating food high in water content helps with overall fluid intake when drinking water is restricted. According to..."',
    enabled: true,
  },
];
